test:
  build: .
  command: make --file=Tests/Makefile test
  environment:
    - PGHOST=data
    - PGUSER=postgres
    - PGPORT=5432
    - CONTAINERIZED=true
  links:
    - data

data:
  image: postgres:9.4
